# require:
#   - rubocop-rspec
#   - ./rubocop/rubocop

# # inherit_from: .rubocop_TODO.yml
# AllCops:
#   Exclude:
#     - db/schema.rb
#     - db/schema*.rb
#   TargetRubyVersion: 2.4

#################### Custom Cops ###########################

#################### Layout ###########################
AllCops:
  NewCops: enable

Layout/IndentationStyle:
  Severity: error
  Enabled: true

Layout/LineLength:
  Max: 200

#################### Style ###########################

# allow define class with nested module like this:
#   module A
#     module B
# to avoid message that alert needed to define like this:
#   module A::B
Style/ClassAndModuleChildren:
  Enabled: false

# allow using `lambda` or `->` for multiple line lambda
Style/Lambda:
  Enabled: false

# Roku and Leonardo think ` > 0 ` is better then `.postive?`
Style/NumericPredicate:
  EnforcedStyle: comparison

# allow extra return, to make code more readable.
#   return a, b
Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Disable enforce single or double quotes.
# 'string'
# "string"
Style/StringLiterals:
  Enabled: false

#################### Metrics ###############################

# allow class length to own a huge code base
Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/AbcSize:
  Max: 100
